// data.js - Base de données complète des agents CleanCo
// Transformé depuis le fichier Python

// Constantes pour l'application
const DATE_AFFECTATION_BASE = "2024-01-01";
const JOURS_FRANCAIS = ['Dim', 'Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'];

const SHIFT_COLORS = {
    '1': '#3498db',    // Bleu pour matin
    '2': '#2ecc71',    // Vert pour après-midi
    '3': '#9b59b6',    // Violet pour nuit
    'R': '#f39c12',    // Orange pour repos
    'C': '#e74c3c',    // Rouge pour congé
    'M': '#e67e22',    // Orange foncé pour maladie
    'A': '#95a5a6',    // Gris pour autre absence
    '-': '#7f8c8d'     // Gris foncé pour non planifié
};

const SHIFT_LABELS = {
    '1': 'Matin',
    '2': 'Après-midi',
    '3': 'Nuit',
    'R': 'Repos',
    'C': 'Congé',
    'M': 'Maladie',
    'A': 'Autre',
    '-': 'Non planifié'
};

// Base de données complète des agents
const agents = [
    // Groupe A
    {
        code: 'CPA',
        nom: 'OUKHA',
        prenom: 'NABIL',
        groupe: 'A',
        tel: '0681564713',
        adresse: 'sala Al jadida',
        code_panique: '',
        poste: 'CP',
        cin: 'A758609',
        date_naissance: '1974-11-05',
        matricule: 'S09278C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'CONA',
        nom: 'EL JAMALI',
        prenom: 'Younes',
        groupe: 'A',
        tel: '0663290648',
        adresse: 'cym',
        code_panique: '',
        poste: 'CON',
        cin: 'A370180',
        date_naissance: '1992-09-04',
        matricule: 'S09425C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'MOTA',
        nom: 'TISSIRT',
        prenom: 'hakim',
        groupe: 'A',
        tel: '0611160166',
        adresse: 'sale',
        code_panique: '',
        poste: 'MOT',
        cin: 'CB230482',
        date_naissance: '1968-10-20',
        matricule: 'S09279C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'ZA',
        nom: 'DRAFA',
        prenom: 'Noureddine',
        groupe: 'A',
        tel: '0603482589',
        adresse: 'tamasna',
        code_panique: '815',
        poste: 'ZA',
        cin: '469875',
        date_naissance: '1974-05-15',
        matricule: 'S09179C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'Z2A',
        nom: 'KAROUCHE',
        prenom: 'Fayçal',
        groupe: 'A',
        tel: '',
        adresse: 'DP1400',
        code_panique: '',
        poste: 'Z2A',
        cin: '743534',
        date_naissance: '',
        matricule: 'S13273C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'Z5A',
        nom: 'LAWRIQAT TARIK',
        prenom: 'TARIK',
        groupe: 'A',
        tel: '0615296161',
        adresse: '',
        code_panique: 'DP1400',
        poste: 'Z5A',
        cin: '794204',
        date_naissance: '1979-04-17',
        matricule: 'S11699C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'Z7A',
        nom: 'CHERKAOUI',
        prenom: 'NOUAMANA',
        groupe: 'A',
        tel: '',
        adresse: 'DP1400',
        code_panique: '',
        poste: 'Z7A',
        cin: 'D216143',
        date_naissance: '1992-12-01',
        matricule: 'S11869C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O1aA',
        nom: 'ALAMI',
        prenom: 'ZAKARIA',
        groupe: 'A',
        tel: '0660269360',
        adresse: '',
        code_panique: '913',
        poste: 'O1a',
        cin: 'D990488',
        date_naissance: '1987-06-02',
        matricule: 'S09188C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O1bA',
        nom: 'EL KADMIRI',
        prenom: 'YASSINE',
        groupe: 'A',
        tel: '0707937021',
        adresse: '',
        code_panique: '228',
        poste: 'O1bA',
        cin: 'A253632',
        date_naissance: '1986-10-22',
        matricule: 'S12667C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O3A',
        nom: 'EL GHALLA',
        prenom: 'ABDELALI',
        groupe: 'A',
        tel: '0663391782',
        adresse: '',
        code_panique: '511',
        poste: 'O3A',
        cin: '729822',
        date_naissance: '1976-06-30',
        matricule: 'S09216C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O8A',
        nom: 'AIT LMKADAM',
        prenom: 'KAHCEN',
        groupe: 'A',
        tel: '0626521862',
        adresse: '',
        code_panique: '824',
        poste: 'O8',
        cin: 'PB42708',
        date_naissance: '1977-11-19',
        matricule: 'S09229C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O9A',
        nom: 'OUTANOUT',
        prenom: 'OMAR',
        groupe: 'A',
        tel: '06943677602',
        adresse: '',
        code_panique: '813',
        poste: 'O9A',
        cin: '651335',
        date_naissance: '1972-01-03',
        matricule: 'S09251C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O10A',
        nom: 'ZOUHRI',
        prenom: 'HAMID',
        groupe: 'A',
        tel: '0625615979',
        adresse: '',
        code_panique: '911',
        poste: 'O10',
        cin: 'Z155268',
        date_naissance: '1968-12-19',
        matricule: 'S09861C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O11A',
        nom: 'ARRADI',
        prenom: 'TARIK',
        groupe: 'A',
        tel: '',
        adresse: '',
        code_panique: '326',
        poste: 'O11A',
        cin: 'A345212',
        date_naissance: '1990-11-25',
        matricule: 'S09284C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O12A',
        nom: 'BOULAHFA',
        prenom: 'MOHAMED',
        groupe: 'A',
        tel: '0667877556',
        adresse: '',
        code_panique: '855',
        poste: 'O12',
        cin: 'FL33963',
        date_naissance: '1965-06-30',
        matricule: 'S09234C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O13A',
        nom: 'ZDIHRI',
        prenom: 'ABDERRAHIM',
        groupe: 'A',
        tel: '0667370493',
        adresse: '',
        code_panique: '826',
        poste: 'O13A',
        cin: 'B187620',
        date_naissance: '1967-11-05',
        matricule: 'S09204C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O15A',
        nom: 'AIT BENALI',
        prenom: 'ABLKRIM',
        groupe: 'A',
        tel: '0641103141',
        adresse: '',
        code_panique: '113',
        poste: 'O15A',
        cin: 'D171008',
        date_naissance: '1987-05-26',
        matricule: 'S12072C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O16A',
        nom: 'HOUMMAY MEHDI',
        prenom: 'MEHDI',
        groupe: 'A',
        tel: '0660994944',
        adresse: '',
        code_panique: '827',
        poste: 'O16A',
        cin: 'A33782',
        date_naissance: '1983-09-22',
        matricule: 'S09159C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L2A',
        nom: 'OUSSALLEM',
        prenom: 'KHALID',
        groupe: 'A',
        tel: '0715929737',
        adresse: '',
        code_panique: '126',
        poste: 'L 2A',
        cin: '653628',
        date_naissance: '1970-07-29',
        matricule: 'S09166C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L5A',
        nom: 'SLYI',
        prenom: 'MOHAMED',
        groupe: 'A',
        tel: '0649068606',
        adresse: '',
        code_panique: '913',
        poste: 'L5A',
        cin: 'B129122',
        date_naissance: '1965-03-22',
        matricule: 'S09212C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L6A',
        nom: 'KHTIDAK',
        prenom: 'HICHAM',
        groupe: 'A',
        tel: '0660124827',
        adresse: '',
        code_panique: '841',
        poste: 'L6A',
        cin: '766806',
        date_naissance: '1977-09-09',
        matricule: 'S09228C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L7A',
        nom: 'ECHOUHAIDI',
        prenom: 'RACHID',
        groupe: 'A',
        tel: '0670444699',
        adresse: '',
        code_panique: '327',
        poste: 'L7A',
        cin: '471850',
        date_naissance: '1974-02-24',
        matricule: 'S09254C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L8A',
        nom: 'ABOUKAL',
        prenom: 'SAID',
        groupe: 'A',
        tel: '0661541861',
        adresse: '',
        code_panique: '815',
        poste: 'L8A',
        cin: '418554',
        date_naissance: '1971-04-11',
        matricule: 'S09207C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L11A',
        nom: 'QOTBI',
        prenom: 'OTMAN',
        groupe: 'A',
        tel: '0681688161',
        adresse: '',
        code_panique: '125',
        poste: 'L11A',
        cin: 'A18238',
        date_naissance: '1986-11-19',
        matricule: 'S09156C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L13A',
        nom: 'ZEHDI',
        prenom: 'SALEM',
        groupe: 'A',
        tel: '0666788715',
        adresse: '',
        code_panique: '118',
        poste: 'L13A',
        cin: '569901',
        date_naissance: '1967-12-01',
        matricule: 'S10068C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L14A',
        nom: 'BOUNHAR',
        prenom: 'MOHAMED',
        groupe: 'A',
        tel: '0614445839',
        adresse: '',
        code_panique: '858',
        poste: 'L14A',
        cin: '772206',
        date_naissance: '1976-04-23',
        matricule: 'S09235C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L15A',
        nom: 'BOUCHRIHA',
        prenom: 'MOUNIR',
        groupe: 'A',
        tel: '0641871461',
        adresse: '',
        code_panique: '999',
        poste: 'L15A',
        cin: '774225',
        date_naissance: '1978-12-04',
        matricule: 'S09424C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L16A',
        nom: 'ROUANI',
        prenom: 'AYOUB',
        groupe: 'A',
        tel: '0612510273',
        adresse: '',
        code_panique: '328',
        poste: 'L16A',
        cin: 'A48291',
        date_naissance: '1991-06-07',
        matricule: 'S09172C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L18A',
        nom: 'EL KAHLAOUI',
        prenom: 'ABDELLAH',
        groupe: 'A',
        tel: '0671415745',
        adresse: '',
        code_panique: '826',
        poste: 'L18A',
        cin: '724698',
        date_naissance: '1975-02-18',
        matricule: 'S09199C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L20A',
        nom: 'FOZARI',
        prenom: 'ABDLILAH',
        groupe: 'A',
        tel: '0690108567',
        adresse: '',
        code_panique: '922',
        poste: 'L 20',
        cin: '',
        date_naissance: '',
        matricule: '',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },

    // Groupe B
    {
        code: 'CPB',
        nom: 'CHMAREKH',
        prenom: 'Noureddine',
        groupe: 'B',
        tel: '0660337343',
        adresse: '',
        code_panique: '854',
        poste: 'CPA',
        cin: '604196',
        date_naissance: '1971-11-24',
        matricule: 'S09274C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'CONB',
        nom: 'IBRAHIMY',
        prenom: 'ABDELLAHADIB',
        groupe: 'B',
        tel: '0662815350',
        adresse: '',
        code_panique: 'DP1400',
        poste: 'CON',
        cin: 'C475743',
        date_naissance: '1976-03-15',
        matricule: 'S09275C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'MOTB',
        nom: 'KAALI',
        prenom: 'MAJID',
        groupe: 'B',
        tel: '0777934644',
        adresse: '',
        code_panique: 'DP1400',
        poste: 'MOT',
        cin: 'Q210329',
        date_naissance: '1978-11-25',
        matricule: 'S12666C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'Z2B',
        nom: 'TSOULI',
        prenom: 'ADIL',
        groupe: 'B',
        tel: '0767872200',
        adresse: '',
        code_panique: 'DP1400',
        poste: 'Z2A',
        cin: '414286',
        date_naissance: '2020-07-01',
        matricule: 'S09170C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'Z5B',
        nom: 'KAMOUN',
        prenom: 'YOUNES',
        groupe: 'B',
        tel: '',
        adresse: '',
        code_panique: 'DP1400',
        poste: 'Z5',
        cin: 'C436844',
        date_naissance: '1971-05-12',
        matricule: 'S09180C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'Z6B',
        nom: 'ROCHDI',
        prenom: 'HASSAN',
        groupe: 'B',
        tel: '065539574',
        adresse: '',
        code_panique: 'DP1400',
        poste: 'z6A',
        cin: '594182',
        date_naissance: '1969-10-15',
        matricule: 'S09173C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O1aB',
        nom: 'JELOULI',
        prenom: 'MAROUAN',
        groupe: 'B',
        tel: '0637401598',
        adresse: '',
        code_panique: '913',
        poste: 'O1a',
        cin: 'AB335545',
        date_naissance: '1986-01-30',
        matricule: 'S09186C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O1bB',
        nom: 'KADI',
        prenom: 'ANNOUAR',
        groupe: 'B',
        tel: '0642889596',
        adresse: '',
        code_panique: '228',
        poste: 'O1b',
        cin: 'AE110942',
        date_naissance: '1990-09-11',
        matricule: 'S12672C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O3B',
        nom: 'EL FADEL',
        prenom: 'MOHAMED',
        groupe: 'B',
        tel: '0762731541',
        adresse: '',
        code_panique: '511',
        poste: 'O3A',
        cin: '783152',
        date_naissance: '1976-12-15',
        matricule: 'S09239C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O4A',
        nom: 'BOUAKRA',
        prenom: 'ABDELHAK',
        groupe: 'A',
        tel: '0673978815',
        adresse: '',
        code_panique: '313',
        poste: 'O4A',
        cin: '758824',
        date_naissance: '1972-02-04',
        matricule: 'S09197C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O5B',
        nom: 'HOUCINE',
        prenom: 'ASGHEN',
        groupe: 'B',
        tel: '0617152230',
        adresse: '',
        code_panique: '848',
        poste: 'O5',
        cin: 'CB42565',
        date_naissance: '1972-10-10',
        matricule: 'S09225C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O8B',
        nom: 'RIFKI',
        prenom: 'KAMAL',
        groupe: 'B',
        tel: '0677019711',
        adresse: '',
        code_panique: '824',
        poste: 'O8',
        cin: 'AB70661',
        date_naissance: '1982-05-26',
        matricule: 'S09185C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O9B',
        nom: 'HADIR',
        prenom: 'HAKIM',
        groupe: 'B',
        tel: '0622379633',
        adresse: '',
        code_panique: '813',
        poste: 'O9',
        cin: 'D217181',
        date_naissance: '1983-06-23',
        matricule: 'S09158C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O10B',
        nom: 'BELASRI',
        prenom: 'MOHAMED',
        groupe: 'B',
        tel: '0670108838',
        adresse: '',
        code_panique: '911',
        poste: 'O10',
        cin: 'A755100',
        date_naissance: '1971-05-25',
        matricule: 'S09244C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O11B',
        nom: 'MANSOURI',
        prenom: 'OUSSAAMA',
        groupe: 'B',
        tel: '0691484070',
        adresse: '',
        code_panique: '326',
        poste: 'O11A',
        cin: '728886',
        date_naissance: '1975-10-20',
        matricule: 'S09956C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O12B',
        nom: 'LAHYANE',
        prenom: 'MOHCINE',
        groupe: 'B',
        tel: '0676454181',
        adresse: '',
        code_panique: '855',
        poste: 'O12A',
        cin: '779095',
        date_naissance: '1981-02-06',
        matricule: 'S12134C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O13B',
        nom: 'ABDOUSSI',
        prenom: 'HASSAN',
        groupe: 'B',
        tel: '0645308599',
        adresse: '',
        code_panique: '826',
        poste: 'O13',
        cin: 'D424329',
        date_naissance: '1973-11-28',
        matricule: 'S09218C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O14B',
        nom: 'ABEID',
        prenom: 'MOHAMED',
        groupe: 'B',
        tel: '0663738283',
        adresse: '',
        code_panique: '838',
        poste: 'O14A',
        cin: '767986',
        date_naissance: '1972-06-12',
        matricule: 'S11698C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O15B',
        nom: 'FAKHAR',
        prenom: 'ABDEHADI',
        groupe: 'B',
        tel: '0648941710',
        adresse: '',
        code_panique: '113',
        poste: 'O15A',
        cin: 'A20765',
        date_naissance: '1988-11-08',
        matricule: 'S11645C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O16B',
        nom: 'NAIM',
        prenom: 'TAOUFIK',
        groupe: 'B',
        tel: '0636552127',
        adresse: '',
        code_panique: '827',
        poste: 'O16A',
        cin: '762084',
        date_naissance: '1972-12-15',
        matricule: 'S09250C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L2B',
        nom: 'ZAHI',
        prenom: 'MOHAMED',
        groupe: 'B',
        tel: '0671614828',
        adresse: '',
        code_panique: '126',
        poste: 'L 2A',
        cin: '566655',
        date_naissance: '1969-03-20',
        matricule: 'S09243C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L4B',
        nom: 'YOUNES',
        prenom: 'KHODAYRA',
        groupe: 'A',
        tel: '0696893480',
        adresse: '',
        code_panique: '842',
        poste: 'L4A',
        cin: '660675',
        date_naissance: '1983-02-10',
        matricule: 'S09162C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L5B',
        nom: 'BELAHMAR',
        prenom: 'MOHAMED',
        groupe: 'B',
        tel: '0676120413',
        adresse: '',
        code_panique: '913',
        poste: 'L5A',
        cin: 'A20765',
        date_naissance: '1988-11-09',
        matricule: 'S11645C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L6B',
        nom: 'RACHAD',
        prenom: 'YOUSSEF',
        groupe: 'B',
        tel: '0608980660',
        adresse: '',
        code_panique: '841',
        poste: 'L6A',
        cin: 'D152284',
        date_naissance: '1986-09-10',
        matricule: 'S09167C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L7B',
        nom: 'ANOUAR',
        prenom: 'KADDAR',
        groupe: 'B',
        tel: '0610425223',
        adresse: '',
        code_panique: '327',
        poste: 'L7A',
        cin: 'B155974',
        date_naissance: '1975-06-10',
        matricule: 'S09161C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L8B',
        nom: 'AHMED',
        prenom: 'OUHADI',
        groupe: 'B',
        tel: '0670469944',
        adresse: '',
        code_panique: '815',
        poste: 'L8',
        cin: 'FL74690',
        date_naissance: '1968-01-01',
        matricule: 'S11697C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L9B',
        nom: 'BOUZIANE',
        prenom: 'EL HAMROUCHI',
        groupe: 'B',
        tel: '0662765085',
        adresse: '',
        code_panique: '914',
        poste: 'L9',
        cin: 'H207682',
        date_naissance: '2005-05-24',
        matricule: 'S12668C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L10B',
        nom: 'ABDELHAK',
        prenom: 'AKRAOUI',
        groupe: 'B',
        tel: '0660387282',
        adresse: '',
        code_panique: '926',
        poste: 'L10',
        cin: 'AD57067',
        date_naissance: '1977-01-01',
        matricule: 'S09382C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L11B',
        nom: 'NOUASSI',
        prenom: 'AHMED',
        groupe: 'B',
        tel: '0666276247',
        adresse: '',
        code_panique: '125',
        poste: 'L11A',
        cin: '319132',
        date_naissance: '1968-01-11',
        matricule: 'S09211C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L13B',
        nom: 'DAOU',
        prenom: 'RACHID',
        groupe: 'B',
        tel: '0677772015',
        adresse: '',
        code_panique: '118',
        poste: 'L13',
        cin: 'X127977',
        date_naissance: '1970-08-01',
        matricule: 'S09253C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L14B',
        nom: 'ABDELGHANI',
        prenom: 'KANOUBI',
        groupe: 'B',
        tel: '0606656164',
        adresse: '',
        code_panique: '858',
        poste: 'L14A',
        cin: '752774',
        date_naissance: '1970-11-28',
        matricule: 'S12670C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L15B',
        nom: 'BOUTJADIR',
        prenom: 'HAMZA',
        groupe: 'B',
        tel: '0615183020',
        adresse: '',
        code_panique: '999',
        poste: 'L15A',
        cin: 'A40770',
        date_naissance: '1987-06-30',
        matricule: 'S09423C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L16B',
        nom: 'NOUREDDINE',
        prenom: 'TAOUZI',
        groupe: 'B',
        tel: '0767872200',
        adresse: '',
        code_panique: '328',
        poste: 'L16A',
        cin: '414286',
        date_naissance: '1970-08-04',
        matricule: 'S09169C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L18B',
        nom: 'ABDELAZIZ',
        prenom: 'SAKANI',
        groupe: 'B',
        tel: '0662509676',
        adresse: '',
        code_panique: '826',
        poste: 'L18',
        cin: 'Z428454',
        date_naissance: '1986-01-10',
        matricule: 'S13153C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L20B',
        nom: 'RACHAKHA',
        prenom: 'SAID',
        groupe: 'B',
        tel: '0648758364',
        adresse: '',
        code_panique: '922',
        poste: 'L 20',
        cin: '',
        date_naissance: '',
        matricule: '',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'ZB',
        nom: 'SNAIDA',
        prenom: 'AHMED',
        groupe: 'B',
        tel: '0666362689',
        adresse: '',
        code_panique: '815',
        poste: 'ZX',
        cin: 'A24831',
        date_naissance: '1974-05-25',
        matricule: 'S09195C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },

    // Groupe C
    {
        code: 'CPC',
        nom: 'ABDELHAK',
        prenom: 'BERRIMA',
        groupe: 'C',
        tel: '0660337343',
        adresse: '',
        code_panique: '854',
        poste: 'CPA',
        cin: '403963',
        date_naissance: '1967-02-24',
        matricule: 'S09271C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'CONC',
        nom: 'NOUR',
        prenom: 'HICHAM',
        groupe: 'C',
        tel: '0665484503',
        adresse: '',
        code_panique: 'DP1400',
        poste: 'CON',
        cin: 'A714632',
        date_naissance: '1982-02-03',
        matricule: 'S09174C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'MOTC',
        nom: 'IDRISS',
        prenom: 'IDRISSI',
        groupe: 'C',
        tel: '0667999548',
        adresse: '',
        code_panique: 'DP1400',
        poste: 'MOT',
        cin: 'AB171068',
        date_naissance: '1972-12-24',
        matricule: 'S09276C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'Z6C',
        nom: 'HARBIL',
        prenom: 'ANASS',
        groupe: 'C',
        tel: '0669001099',
        adresse: '',
        code_panique: 'DP1400',
        poste: 'z6A',
        cin: '434690',
        date_naissance: '1984-02-26',
        matricule: 'S09153C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'Z2C',
        nom: 'GRINEH',
        prenom: 'KHALID',
        groupe: 'C',
        tel: '',
        adresse: '',
        code_panique: 'DP1400',
        poste: 'Z2A',
        cin: '670880',
        date_naissance: '1976-09-29',
        matricule: 'S09176C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'Z5C',
        nom: 'MULouANI',
        prenom: 'MUSTAPHA',
        groupe: 'C',
        tel: '0661970781',
        adresse: '',
        code_panique: 'DP1400',
        poste: 'Z5',
        cin: 'AB96201',
        date_naissance: '1969-11-18',
        matricule: 'S09165C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'Z6A',
        nom: 'MOHAMED',
        prenom: 'MOUSTAKIM',
        groupe: 'A',
        tel: '0654718291',
        adresse: '',
        code_panique: 'DP1400',
        poste: 'z6A',
        cin: '764411',
        date_naissance: '1975-07-15',
        matricule: 'S09246C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O1aC',
        nom: 'JAOUAD',
        prenom: 'ELKERRAOUI',
        groupe: 'C',
        tel: '',
        adresse: '',
        code_panique: '913',
        poste: 'O1a',
        cin: 'A471219',
        date_naissance: '1973-10-21',
        matricule: 'S09184C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O1bC',
        nom: 'AZIZ',
        prenom: 'CHOUKAIRI',
        groupe: 'C',
        tel: '0637014737',
        adresse: '',
        code_panique: '228',
        poste: 'O1b',
        cin: '',
        date_naissance: '1966-04-22',
        matricule: 'S09196C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O3C',
        nom: 'YOUNESS',
        prenom: 'MAKAN',
        groupe: 'C',
        tel: '0624125461',
        adresse: '',
        code_panique: '511',
        poste: 'O3A',
        cin: '0704268',
        date_naissance: '1977-07-03',
        matricule: 'S09262C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O4C',
        nom: 'BRAHIM',
        prenom: 'HMIJAN',
        groupe: 'C',
        tel: '0678490326',
        adresse: '',
        code_panique: '313',
        poste: 'O4',
        cin: '',
        date_naissance: '1985-04-18',
        matricule: 'S09214C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O5C',
        nom: 'YOUSSEF',
        prenom: 'ATTOUMI',
        groupe: 'C',
        tel: '0676800556',
        adresse: '',
        code_panique: '848',
        poste: 'O5',
        cin: 'QA28049',
        date_naissance: '1970-03-20',
        matricule: 'S09263C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O8C',
        nom: 'TOUFIQ',
        prenom: 'TAOUFIKI',
        groupe: 'C',
        tel: '0656935477',
        adresse: '',
        code_panique: '824',
        poste: 'O8',
        cin: 'BE584375',
        date_naissance: '1971-08-01',
        matricule: 'S09249C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O9C',
        nom: 'MOHAMED',
        prenom: 'ELYOUSSFI',
        groupe: 'C',
        tel: '06666624637',
        adresse: '',
        code_panique: '813',
        poste: 'O9',
        cin: 'D148238',
        date_naissance: '1985-02-05',
        matricule: 'S09217C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O10C',
        nom: 'MOHAMED',
        prenom: 'KHTIDAK',
        groupe: 'C',
        tel: '0661564216',
        adresse: '',
        code_panique: '911',
        poste: 'O10',
        cin: 'A315369',
        date_naissance: '1966-09-14',
        matricule: 'S09270C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O11C',
        nom: 'MUSTAPHA',
        prenom: 'ARIBATE',
        groupe: 'C',
        tel: '0660413159',
        adresse: '',
        code_panique: '326',
        poste: 'O11A',
        cin: '755764',
        date_naissance: '1973-12-21',
        matricule: 'S09178C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O13C',
        nom: 'HAMID',
        prenom: 'SAIB',
        groupe: 'C',
        tel: '0642234491',
        adresse: '',
        code_panique: '826',
        poste: 'O13',
        cin: 'AB812110',
        date_naissance: '1984-06-30',
        matricule: 'S09168C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O14C',
        nom: 'RACHID',
        prenom: 'ALOUI',
        groupe: 'C',
        tel: '0675660099',
        adresse: '',
        code_panique: '838',
        poste: 'O14A',
        cin: 'AB192453',
        date_naissance: '1972-06-30',
        matricule: 'S09252C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O15C',
        nom: 'YOUSSEF',
        prenom: 'ZOURAKI',
        groupe: 'C',
        tel: '0663868378',
        adresse: '',
        code_panique: '113',
        poste: 'O15A',
        cin: 'A441336',
        date_naissance: '1992-03-12',
        matricule: 'S09171C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O16C',
        nom: 'ENNABAL',
        prenom: 'AZOUZ',
        groupe: 'C',
        tel: '0698853826',
        adresse: '',
        code_panique: '827',
        poste: 'O16A',
        cin: '566483',
        date_naissance: '1967-01-04',
        matricule: 'S09291C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L2C',
        nom: 'ELHILALI',
        prenom: 'AKRAM',
        groupe: 'C',
        tel: '0662665394',
        adresse: '',
        code_panique: '126',
        poste: 'L 2A',
        cin: '427172',
        date_naissance: '1976-01-26',
        matricule: 'S12073C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L4C',
        nom: 'RACHID',
        prenom: 'MAGHAT',
        groupe: 'C',
        tel: '',
        adresse: '',
        code_panique: '842',
        poste: 'L4',
        cin: '',
        date_naissance: '',
        matricule: '',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L5C',
        nom: 'ABDERRAHIL',
        prenom: 'FAKUHI',
        groupe: 'C',
        tel: '0662665394',
        adresse: '',
        code_panique: '126',
        poste: 'L 2A',
        cin: '427172',
        date_naissance: '1976-01-26',
        matricule: 'S12073C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L6C',
        nom: 'RACHID',
        prenom: 'NOUR',
        groupe: 'C',
        tel: '0662665394',
        adresse: '',
        code_panique: '126',
        poste: 'L 2A',
        cin: '427172',
        date_naissance: '1976-01-26',
        matricule: 'S12073C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L7C',
        nom: 'MOHAMED',
        prenom: 'NAZIR',
        groupe: 'C',
        tel: '0662665394',
        adresse: '',
        code_panique: '126',
        poste: 'L 2A',
        cin: '427172',
        date_naissance: '1976-01-26',
        matricule: 'S12073C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L8C',
        nom: 'HASSAN',
        prenom: 'ASSLOUH',
        groupe: 'C',
        tel: '0662665394',
        adresse: '',
        code_panique: '126',
        poste: 'L 2A',
        cin: '427172',
        date_naissance: '1976-01-26',
        matricule: 'S12073C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L9C',
        nom: 'IKHLOUFEN',
        prenom: 'MOUNIR',
        groupe: 'C',
        tel: '0762695160',
        adresse: '',
        code_panique: '914',
        poste: 'L9A',
        cin: 'E234817',
        date_naissance: '1996-06-17',
        matricule: 'S12075C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L10C',
        nom: 'DRISS',
        prenom: 'BENGHANMI',
        groupe: 'C',
        tel: '0660201164',
        adresse: '',
        code_panique: '926',
        poste: 'L10',
        cin: 'AB532578',
        date_naissance: '1986-01-01',
        matricule: 'S12131C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L11C',
        nom: 'LARBI',
        prenom: 'LKWISSI',
        groupe: 'C',
        tel: '0662382842',
        adresse: '',
        code_panique: '125',
        poste: 'L11',
        cin: 'MC13001',
        date_naissance: '1980-07-03',
        matricule: 'S09233C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L13C',
        nom: 'ABDELLAH',
        prenom: 'TABTI',
        groupe: 'C',
        tel: '0663229985',
        adresse: '',
        code_panique: '118',
        poste: 'L13',
        cin: 'AD56680',
        date_naissance: '1979-01-01',
        matricule: 'S09194C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L14C',
        nom: 'ABDEMOUNIM',
        prenom: 'MNAM',
        groupe: 'C',
        tel: '0664914374',
        adresse: '',
        code_panique: '858',
        poste: 'L14A',
        cin: '727413',
        date_naissance: '1977-11-04',
        matricule: 'S09203C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L15C',
        nom: 'TOUFIK',
        prenom: 'ALHAFID',
        groupe: 'C',
        tel: '0662888444',
        adresse: '',
        code_panique: '999',
        poste: 'L15A',
        cin: 'B197016',
        date_naissance: '1975-02-04',
        matricule: 'S09260C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L16C',
        nom: 'AZIZ',
        prenom: 'ELALOUSSI',
        groupe: 'C',
        tel: '0661098728',
        adresse: '',
        code_panique: '328',
        poste: 'L16',
        cin: 'Z428454',
        date_naissance: '',
        matricule: '',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L18C',
        nom: 'ABDELAZIZ',
        prenom: 'SAKANI',
        groupe: 'C',
        tel: '0662509676',
        adresse: '',
        code_panique: '826',
        poste: 'L18',
        cin: 'A203082',
        date_naissance: '1961-03-10',
        matricule: 'RETRAITE',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'inactif'
    },
    {
        code: 'L20C',
        nom: 'FARASSI',
        prenom: 'KARIM',
        groupe: 'C',
        tel: '0635419761',
        adresse: '',
        code_panique: '922',
        poste: 'L 20',
        cin: '',
        date_naissance: '',
        matricule: '',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },

    // Groupe D
    {
        code: 'CPD',
        nom: 'mouhcine',
        prenom: 'YAGOUB',
        groupe: 'D',
        tel: '0660336995',
        adresse: '',
        code_panique: '854',
        poste: 'CPA',
        cin: '0408930',
        date_naissance: '1966-05-17',
        matricule: 'S09272C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'COND',
        nom: 'HOUSSAIN',
        prenom: 'ALAHYANE',
        groupe: 'D',
        tel: '0668191854',
        adresse: '',
        code_panique: 'DP1400',
        poste: 'CON',
        cin: 'JB49050',
        date_naissance: '1966-01-01',
        matricule: 'S09280C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'MOTD',
        nom: 'LAHCEN',
        prenom: 'ALAMI',
        groupe: 'D',
        tel: '0666195501',
        adresse: '',
        code_panique: 'DP1400',
        poste: 'MOT',
        cin: 'UA97962',
        date_naissance: '1967-06-24',
        matricule: 'S09277C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'ZD',
        nom: 'MOULZY',
        prenom: 'mehdi',
        groupe: 'D',
        tel: '0665233677',
        adresse: '',
        code_panique: '815',
        poste: 'Z',
        cin: 'AB47887',
        date_naissance: '1968-01-15',
        matricule: 'S09268C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'Z2D',
        nom: 'MUSTAPHA',
        prenom: 'BOUTSON',
        groupe: 'D',
        tel: '',
        adresse: '',
        code_panique: 'DP1400',
        poste: 'Z2A',
        cin: '692457',
        date_naissance: '1980-02-14',
        matricule: 'S09290C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'Z5D',
        nom: 'AYOUB',
        prenom: 'MAHDAD',
        groupe: 'D',
        tel: '0682153784',
        adresse: '',
        code_panique: 'DP1400',
        poste: 'Z5',
        cin: 'AD210108',
        date_naissance: '1990-03-23',
        matricule: 'S11995C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'Z6D',
        nom: 'ABDELHAQ',
        prenom: 'ZEROUAL',
        groupe: 'D',
        tel: '0605119496',
        adresse: '',
        code_panique: 'DP1400',
        poste: 'z6',
        cin: 'I495670',
        date_naissance: '1979-08-13',
        matricule: 'S09205C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O1aD',
        nom: 'IMAD',
        prenom: 'BEN KHADRA',
        groupe: 'D',
        tel: '0682153784',
        adresse: '',
        code_panique: '913',
        poste: 'O1a',
        cin: 'AB624802',
        date_naissance: '1987-02-12',
        matricule: 'S12674C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O1bD',
        nom: 'KHLIFI',
        prenom: 'HADARBACH',
        groupe: 'D',
        tel: '0670059528',
        adresse: '',
        code_panique: '228',
        poste: 'O1b',
        cin: 'UA95212',
        date_naissance: '1968-04-22',
        matricule: 'S09190C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O3D',
        nom: 'YAHYA',
        prenom: 'ABARKAN',
        groupe: 'D',
        tel: '0650651681',
        adresse: '',
        code_panique: '511',
        poste: 'O3A',
        cin: '632213',
        date_naissance: '1976-12-15',
        matricule: 'S09261C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'NO4D',
        nom: 'MOHAMED',
        prenom: 'KABDANI',
        groupe: 'D',
        tel: '0611658102',
        adresse: '',
        code_panique: '313',
        poste: 'O4A',
        cin: '427567',
        date_naissance: '1976-03-28',
        matricule: 'S09240C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O8D',
        nom: 'LAHCEN',
        prenom: 'EL KABOURI',
        groupe: 'D',
        tel: '0663754454',
        adresse: '',
        code_panique: '824',
        poste: 'O8A',
        cin: '0365454',
        date_naissance: '1979-07-14',
        matricule: 'S09230C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O9D',
        nom: 'HAKIM',
        prenom: 'HADDIR',
        groupe: 'D',
        tel: '0677522349',
        adresse: '',
        code_panique: '813',
        poste: 'O9',
        cin: 'D217181',
        date_naissance: '1990-06-23',
        matricule: 'S09158C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O10D',
        nom: 'ADIL',
        prenom: 'LOURIGHI',
        groupe: 'D',
        tel: '0652869687',
        adresse: '',
        code_panique: '911',
        poste: 'O10',
        cin: 'A742130',
        date_naissance: '1994-02-19',
        matricule: 'S12133C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O11D',
        nom: 'TOUFIK',
        prenom: 'HAJJI',
        groupe: 'D',
        tel: '0660024350',
        adresse: '',
        code_panique: '326',
        poste: 'O11A',
        cin: '679901',
        date_naissance: '1983-08-15',
        matricule: 'S09258C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O12D',
        nom: 'HASSAN',
        prenom: 'TOUNSSI',
        groupe: 'D',
        tel: '0668928626',
        adresse: '',
        code_panique: '855',
        poste: 'O12A',
        cin: '194910',
        date_naissance: '1962-07-01',
        matricule: 'S09223C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O13D',
        nom: 'HASSAN',
        prenom: 'CHAMI',
        groupe: 'D',
        tel: '0622564794',
        adresse: '',
        code_panique: '826',
        poste: 'O13',
        cin: '',
        date_naissance: '1966-01-01',
        matricule: 'S09215C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O14D',
        nom: 'MUSTAPHA',
        prenom: 'OUGHIL',
        groupe: 'D',
        tel: '0677651378',
        adresse: '',
        code_panique: '838',
        poste: 'O14',
        cin: 'D523912',
        date_naissance: '1979-02-12',
        matricule: 'S09248C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O15D',
        nom: 'ABDERAHIM',
        prenom: 'MACHHAB',
        groupe: 'D',
        tel: '0668272975',
        adresse: '',
        code_panique: '113',
        poste: 'O15',
        cin: 'E505332',
        date_naissance: '1974-07-03',
        matricule: 'S09164C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'O16D',
        nom: 'BOULDGAG',
        prenom: 'D',
        groupe: 'D',
        tel: '0670357654',
        adresse: '',
        code_panique: '827',
        poste: 'O16',
        cin: 'D388632',
        date_naissance: '1968-01-01',
        matricule: 'S09191C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L2D',
        nom: 'MOLAY AHMED',
        prenom: 'HANSALI',
        groupe: 'D',
        tel: '',
        adresse: '',
        code_panique: '126',
        poste: 'L 2',
        cin: 'I196324',
        date_naissance: '1967-10-01',
        matricule: 'S12671C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L4D',
        nom: 'ABDELJALIL',
        prenom: 'ERRAISSY',
        groupe: 'D',
        tel: '',
        adresse: '',
        code_panique: '842',
        poste: 'L4',
        cin: 'JC337475',
        date_naissance: '',
        matricule: 'S13885C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L5D',
        nom: 'MOHMED',
        prenom: 'EL AISSAOUI',
        groupe: 'D',
        tel: '0666904691',
        adresse: '',
        code_panique: '913',
        poste: 'L5',
        cin: 'AB26585',
        date_naissance: '1962-06-30',
        matricule: 'S09238C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L6D',
        nom: 'MAJID',
        prenom: 'SIYADI',
        groupe: 'D',
        tel: '0664619176',
        adresse: '',
        code_panique: '841',
        poste: 'L6',
        cin: 'BK11512',
        date_naissance: '1962-08-06',
        matricule: 'S09201C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L7D',
        nom: 'HASSAN',
        prenom: 'AIT BOURI',
        groupe: 'D',
        tel: '0641103141',
        adresse: '',
        code_panique: '327',
        poste: 'L7A',
        cin: '406039',
        date_naissance: '1966-02-11',
        matricule: 'S09219C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L9D',
        nom: 'KARIM',
        prenom: 'MEROURI',
        groupe: 'D',
        tel: '0639284992',
        adresse: '',
        code_panique: '914',
        poste: 'L9',
        cin: 'AB11225',
        date_naissance: '',
        matricule: 'S15251C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L10D',
        nom: 'MOHAMED',
        prenom: 'DAHANI',
        groupe: 'D',
        tel: '0608246402',
        adresse: '',
        code_panique: '926',
        poste: 'L10A',
        cin: '756477',
        date_naissance: '1974-03-07',
        matricule: 'S09237C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L11D',
        nom: 'MOHAMED',
        prenom: 'LACHGAR',
        groupe: 'D',
        tel: '0662721021',
        adresse: '',
        code_panique: '125',
        poste: 'L11A',
        cin: 'AB122686',
        date_naissance: '1968-03-17',
        matricule: 'S09189C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L13D',
        nom: 'HICHAM',
        prenom: 'EL HILALI',
        groupe: 'D',
        tel: '0649835024',
        adresse: '',
        code_panique: '118',
        poste: 'L13',
        cin: 'AD35116',
        date_naissance: '1973-02-02',
        matricule: 'S09224C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L14D',
        nom: 'MOHAMED',
        prenom: 'ELHARBI',
        groupe: 'D',
        tel: '0613535275',
        adresse: '',
        code_panique: '858',
        poste: 'L14A',
        cin: 'AB208044',
        date_naissance: '1978-08-05',
        matricule: 'S09245C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L15D',
        nom: 'JALAL',
        prenom: 'DAHBI',
        groupe: 'D',
        tel: '0672792404',
        adresse: '',
        code_panique: '999',
        poste: 'L15A',
        cin: '768009',
        date_naissance: '1976-12-05',
        matricule: 'S09226C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L16D',
        nom: 'RACHID',
        prenom: 'JABAL',
        groupe: 'D',
        tel: '0628612647',
        adresse: '',
        code_panique: '328',
        poste: 'L16A',
        cin: '786241',
        date_naissance: '1979-08-01',
        matricule: 'S09255C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L18D',
        nom: 'MOHAMED',
        prenom: 'GUARMA',
        groupe: 'D',
        tel: '0699082100',
        adresse: '',
        code_panique: '826',
        poste: 'L18',
        cin: 'AD200164',
        date_naissance: '1987-02-20',
        matricule: 'S12074C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'L20D',
        nom: 'BRAHIM',
        prenom: 'SATANI',
        groupe: 'D',
        tel: '0660082965',
        adresse: '',
        code_panique: '922',
        poste: 'L 20',
        cin: '',
        date_naissance: '',
        matricule: '',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },

    // Groupe E
    {
        code: 'ACCA',
        nom: 'CHAJAI',
        prenom: 'SOUKAINA',
        groupe: 'E',
        tel: '',
        adresse: '',
        code_panique: 'non',
        poste: 'D.U.E',
        cin: '',
        date_naissance: '',
        matricule: '',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'ACCB',
        nom: 'MAAROUF',
        prenom: 'NAJAT',
        groupe: 'E',
        tel: '',
        adresse: '',
        code_panique: 'non',
        poste: 'D.U.E',
        cin: 'AD223954',
        date_naissance: '1991-12-06',
        matricule: 'S10100C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'Z1A',
        nom: 'FARROUCHE',
        prenom: 'MILOUD',
        groupe: 'E',
        tel: '',
        adresse: '',
        code_panique: 'dp1400',
        poste: 'D.U.E',
        cin: 'AA31133',
        date_naissance: '1987-11-05',
        matricule: 'S09286C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'Z1B',
        nom: 'KHIAR',
        prenom: 'NOUREDDINE',
        groupe: 'E',
        tel: '',
        adresse: '',
        code_panique: 'dp1401',
        poste: 'D.U.E',
        cin: 'h705007',
        date_naissance: '1991-09-09',
        matricule: 'S12664C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'Z4A',
        nom: 'ECHALLI',
        prenom: 'KASSEM',
        groupe: 'E',
        tel: '',
        adresse: '',
        code_panique: 'dp1402',
        poste: 'D.U.E',
        cin: 'A724455',
        date_naissance: '1985-08-01',
        matricule: 'S12665C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'Z4B',
        nom: 'OUHADI',
        prenom: 'LAHCEN',
        groupe: 'E',
        tel: '',
        adresse: '',
        code_panique: 'dp1403',
        poste: 'D.U.E',
        cin: 'U99650',
        date_naissance: '1973-08-12',
        matricule: 'S09992C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'Z4C',
        nom: 'ELFAKHAR',
        prenom: 'MOHAMED',
        groupe: 'E',
        tel: '',
        adresse: '',
        code_panique: 'dp1404',
        poste: 'D.U.E',
        cin: 'A737428',
        date_naissance: '1983-07-03',
        matricule: 'S09285C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'Z4D',
        nom: 'TAOUIL',
        prenom: 'KHALID',
        groupe: 'E',
        tel: '',
        adresse: '',
        code_panique: 'dp1405',
        poste: 'D.U.E',
        cin: 'AD154017',
        date_naissance: '1988-03-09',
        matricule: 'S10666C',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    },
    {
        code: 'PR',
        nom: 'OUNASSE',
        prenom: 'NAWFAL',
        groupe: 'E',
        tel: '',
        adresse: 'C.T.R',
        code_panique: '',
        poste: '',
        cin: '',
        date_naissance: '',
        matricule: '',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: null,
        statut: 'actif'
    }
];

// Agents retraités (à marquer comme inactifs)
const agentsRetraites = [
    {
        code: 'O4B',
        nom: 'ANQACH HASSAN',
        prenom: 'HASSAN',
        groupe: 'B',
        tel: '',
        adresse: '313',
        code_panique: '',
        poste: 'O4',
        cin: 'non',
        date_naissance: '1962-04-09',
        matricule: 'RETRAITE',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: new Date().toISOString().split('T')[0],
        statut: 'inactif'
    },
    {
        code: 'O5A',
        nom: 'LEKHEL',
        prenom: 'RACHID',
        groupe: 'A',
        tel: '0644734747',
        adresse: '',
        code_panique: '848',
        poste: 'O5',
        cin: 'non',
        date_naissance: '1962-12-04',
        matricule: 'RETRAITE',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: new Date().toISOString().split('T')[0],
        statut: 'inactif'
    },
    {
        code: 'O14A',
        nom: 'EL KHAOUI',
        prenom: 'ABDELTIF',
        groupe: 'A',
        tel: '0670768055',
        adresse: '',
        code_panique: '838',
        poste: 'O14',
        cin: 'non',
        date_naissance: '1961-04-25',
        matricule: 'RETRAITE',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: new Date().toISOString().split('T')[0],
        statut: 'inactif'
    },
    {
        code: 'L10A',
        nom: 'AMHZOUL',
        prenom: 'MUSTAPHA',
        groupe: 'A',
        tel: '0707331929',
        adresse: '',
        code_panique: '926',
        poste: 'L10',
        cin: '',
        date_naissance: '1961-09-28',
        matricule: 'RETRAITE',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: new Date().toISOString().split('T')[0],
        statut: 'inactif'
    },
    {
        code: 'O12C',
        nom: 'AZERFI',
        prenom: 'SAID',
        groupe: 'C',
        tel: '0672499982',
        adresse: '',
        code_panique: '855',
        poste: 'O12',
        cin: '',
        date_naissance: '1961-06-30',
        matricule: 'RETRAITE',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: new Date().toISOString().split('T')[0],
        statut: 'inactif'
    },
    {
        code: 'O5D',
        nom: 'FERZOUI',
        prenom: 'KHALED',
        groupe: 'D',
        tel: '0676745704',
        adresse: '',
        code_panique: '848',
        poste: 'O5',
        cin: '',
        date_naissance: '1962-01-01',
        matricule: 'RETRAITE',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: new Date().toISOString().split('T')[0],
        statut: 'inactif'
    },
    {
        code: 'L8D',
        nom: 'BOUTOU',
        prenom: 'MOHAMED',
        groupe: 'D',
        tel: '0670181844',
        adresse: '',
        code_panique: '815',
        poste: 'L8',
        cin: '',
        date_naissance: '1961-06-30',
        matricule: 'RETRAITE',
        date_entree: DATE_AFFECTATION_BASE,
        date_sortie: new Date().toISOString().split('T')[0],
        statut: 'inactif'
    }
];

// Ajouter les retraités à la liste des agents
agentsRetraites.forEach(retraite => {
    agents.push(retraite);
});

// Initialiser les données de planning
const planningData = {};

// Initialiser les autres données
let panicCodes = [];
let radios = [];
let uniforms = [];
let warnings = [];
let leaves = [];
let radioHistory = [];

// Jours fériés Maroc (année courante)
const currentYear = new Date().getFullYear();
const holidays = [
    { date: `${currentYear}-01-01`, description: 'Nouvel An', type: 'fixe' },
    { date: `${currentYear}-01-11`, description: 'Manifeste de l\'Indépendance', type: 'fixe' },
    { date: `${currentYear}-05-01`, description: 'Fête du Travail', type: 'fixe' },
    { date: `${currentYear}-07-30`, description: 'Fête du Trône', type: 'fixe' },
    { date: `${currentYear}-08-14`, description: 'Allégeance Oued Eddahab', type: 'fixe' },
    { date: `${currentYear}-08-20`, description: 'Révolution du Roi et du Peuple', type: 'fixe' },
    { date: `${currentYear}-08-21`, description: 'Fête de la Jeunesse', type: 'fixe' },
    { date: `${currentYear}-11-06`, description: 'Marche Verte', type: 'fixe' },
    { date: `${currentYear}-11-18`, description: 'Fête de l\'Indépendance', type: 'fixe' }
];

// Fonction pour initialiser les codes panique automatiquement
function initializePanicCodes() {
    panicCodes = [];
    
    agents.forEach(agent => {
        if (agent.code_panique && agent.code_panique !== '' && agent.code_panique !== 'non' && agent.code_panique !== 'DP1400') {
            panicCodes.push({
                agent_code: agent.code,
                code: agent.code_panique,
                poste: agent.poste,
                created_at: new Date().toISOString().split('T')[0],
                updated_at: new Date().toISOString()
            });
        }
    });
}

// Fonction pour initialiser les radios automatiquement
function initializeRadios() {
    radios = [
        {
            id: 'RAD001',
            modele: 'Motorola XPR 7550',
            serial: 'SN001',
            statut: 'DISPONIBLE',
            acquisition_date: '2023-01-15'
        },
        {
            id: 'RAD002',
            modele: 'Motorola XPR 7550',
            serial: 'SN002',
            statut: 'DISPONIBLE',
            acquisition_date: '2023-01-15'
        },
        {
            id: 'RAD003',
            modele: 'Motorola XPR 7550',
            serial: 'SN003',
            statut: 'DISPONIBLE',
            acquisition_date: '2023-01-15'
        },
        {
            id: 'RAD004',
            modele: 'Motorola XPR 7550',
            serial: 'SN004',
            statut: 'DISPONIBLE',
            acquisition_date: '2023-01-15'
        },
        {
            id: 'RAD005',
            modele: 'Motorola XPR 7550',
            serial: 'SN005',
            statut: 'ATTRIBUÉE',
            attributed_to: 'CPA',
            attribution_date: new Date().toISOString().split('T')[0],
            attribution_motif: 'Service normal',
            acquisition_date: '2023-01-15'
        }
    ];
}

// Fonction pour initialiser l'habillement automatiquement
function initializeUniforms() {
    uniforms = [];
    
    // Créer des tailles aléatoires pour chaque agent
    agents.forEach(agent => {
        if (agent.statut === 'actif') {
            const taillesChemise = ['XS', 'S', 'M', 'L', 'XL', 'XXL'];
            const taillesPantalon = ['38', '40', '42', '44', '46', '48'];
            const taillesJacket = ['S', 'M', 'L', 'XL', 'XXL'];
            
            const uniform = {
                agent_code: agent.code,
                chemise_taille: taillesChemise[Math.floor(Math.random() * taillesChemise.length)],
                chemise_date: '2024-01-15',
                pantalon_taille: taillesPantalon[Math.floor(Math.random() * taillesPantalon.length)],
                pantalon_date: '2024-01-15',
                jacket_taille: taillesJacket[Math.floor(Math.random() * taillesJacket.length)],
                jacket_date: '2024-01-15',
                cravate_oui: Math.random() > 0.5,
                cravate_date: '2024-01-15',
                remarques: '',
                updated_at: new Date().toISOString()
            };
            
            uniforms.push(uniform);
        }
    });
}

// Fonction pour initialiser quelques avertissements
function initializeWarnings() {
    warnings = [
        {
            id: 'WARN001',
            agent_code: 'L16A',
            type: 'ORAL',
            date: '2024-01-15',
            description: 'Retard répété au poste',
            sanctions: 'Avertissement oral',
            status: 'active',
            created_at: '2024-01-15',
            created_by: 'Admin'
        },
        {
            id: 'WARN002',
            agent_code: 'O9A',
            type: 'ECRIT',
            date: '2024-02-20',
            description: 'Non-respect des consignes de sécurité',
            sanctions: 'Avertissement écrit',
            status: 'active',
            created_at: '2024-02-20',
            created_by: 'Admin'
        }
    ];
}

// Initialiser toutes les données
initializePanicCodes();
initializeRadios();
initializeUniforms();
initializeWarnings();

console.log(`✅ Base de données chargée avec ${agents.length} agents`);
console.log(`📊 Répartition par groupe:`);
const groupesStats = agents.reduce((acc, agent) => {
    acc[agent.groupe] = (acc[agent.groupe] || 0) + 1;
    return acc;
}, {});
Object.keys(groupesStats).forEach(groupe => {
    console.log(`   Groupe ${groupe}: ${groupesStats[groupe]} agents`);
});
console.log(`🔐 ${panicCodes.length} codes panique initialisés`);
console.log(`📻 ${radios.length} radios initialisées`);
console.log(`👔 ${uniforms.length} fiches habillement initialisées`);
console.log(`⚠️ ${warnings.length} avertissements initialisés`);
